# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-28 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='id',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_num',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
